spring.application.name=ev_charge

# DB
spring.datasource.url=jdbc:mysql://localhost:3306/ev_charging
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# 포트
server.port=8383

logging.level.org.springframework.security=DEBUG

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=680395168132-fd9b6ae3edte7be7unbv0rm7qpi8eg9c.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile